### ISSUE TITLE
Bot hits channel edit ratelimit

### ISSUE THREAD

**Issue by 1980s-housewife** [IPD-Dev/discst#1]
![image](https://user-images.githubusercontent.com/17932849/183616849-6978d535-3eb9-4b06-8323-e2d2af1973d1.png)
![image](https://user-images.githubusercontent.com/17932849/183616878-534cc7c9-419f-4a94-bcea-ce8682581b88.png)
EDIT: It seems that it just couldn't edit the VC for some reason, creating a new vc fixed this issue

**Comment by allinkdev** [comment]
Because ratelimits exist...

**Comment by xfnw** [comment]
does setting the `interval` option to higher than the limit fix this?

if not, i suppose i could just make it only edit the channel if the status changes

**Comment by allinkdev** [comment]
> if not, i suppose i could just make it only edit the channel if the status changes
Would be appreciated, as I believe you'll get ratelimited even if you don't make any changes in your request to edit the channel name.

**Comment by 1980s-housewife** [comment]
can confirm it's ratelimited again, making it edit only if the status changes would be nice :p
